test: Add E2E tests

diff --git a/.github/workflows/test-e2e.yml b/.github/workflows/test-e2e.yml
--- a/.github/workflows/test-e2e.yml
+++ b/.github/workflows/test-e2e.yml
@@ -8,6 +8,7 @@ on:
   push:
     branches:
       - main
+      - test/unit
 
 permissions:
   contents: read
@@ -27,5 +28,26 @@ jobs:
         id: check-spdx-headers
         uses: ./
 
-      # TODO: Add E2E tests, checking the output of different configurations
-      # We could use a github-script action to parse the json report and check the results of each different configuration
+      - name: Test SPDX headers - Case 1
+        id: test-spdx-headers-01
+        uses: ./
+        with:
+          rules: |
+            - name: "Source code"
+              headers:
+                - files:
+                    - "**/*.ts"
+                  license: "MIT"
+          ignore: |
+            - "**/node_modules/**"
+            - "**/dist/**"
+          log: "debug"
+          reporter: "json"
+          failOnNotValid: false
+
+      - name: Check SPDX headers - Case 1
+        env:
+          report: ${{ fromJson(steps.test-spdx-headers-01.outputs.report) }}
+        if: env.report.valid == true || env.report.invalidFiles != 5
+        run: |
+          echo "Test case 1 failed: ${{ toJson(env.report) }}" && exit 1
