test: Add E2E test checking invalid copyright

diff --git a/.github/workflows/test-e2e.yml b/.github/workflows/test-e2e.yml
--- a/.github/workflows/test-e2e.yml
+++ b/.github/workflows/test-e2e.yml
@@ -62,3 +62,47 @@ jobs:
         if: fromJson(steps.test-spdx-headers-01.outputs.report).invalidFiles != 15
         run: |
           echo "Test case 1 failed. The check should have found 15 invalid files, but it found ${{ fromJson(steps.test-spdx-headers-01.outputs.report).invalidFiles }}" && exit 1
+      
+      - name: Test - Case 1 - Assert 3 failed
+        if: fromJson(steps.test-spdx-headers-01.outputs.report).validFiles != 0
+        run: |
+          echo "Test case 1 failed. The check should have found 0 valid files, but it found ${{ fromJson(steps.test-spdx-headers-01.outputs.report).validFiles }}" && exit 1
+
+      - name: Test - Case 2
+        id: test-spdx-headers-02
+        uses: ./
+        with:
+          rules: |
+            [
+              {
+                "name":"Source code",
+                "headers":
+                  [
+                    {
+                      "files":["**/*.ts"],
+                      "copyright": "Foo"
+                    }
+                  ]
+              }
+            ]
+          ignore: |
+            - "**/node_modules/**"
+            - "**/dist/**"
+          log: "debug"
+          reporter: "json"
+          fail-on-not-valid: false
+
+      - name: Test - Case 2 - Assert 1 failed
+        if: fromJson(steps.test-spdx-headers-01.outputs.report).valid == true
+        run: |
+          echo "Test case 2 failed. The check did not found errors" && exit 1
+
+      - name: Test - Case 2 - Assert 2 failed
+        if: fromJson(steps.test-spdx-headers-01.outputs.report).invalidFiles != 15
+        run: |
+          echo "Test case 2 failed. The check should have found 15 invalid files, but it found ${{ fromJson(steps.test-spdx-headers-01.outputs.report).invalidFiles }}" && exit 1
+      
+      - name: Test - Case 2 - Assert 3 failed
+        if: fromJson(steps.test-spdx-headers-01.outputs.report).validFiles != 0
+        run: |
+          echo "Test case 2 failed. The check should have found 0 valid files, but it found ${{ fromJson(steps.test-spdx-headers-01.outputs.report).validFiles }}" && exit 1
